SELECT *
FROM EMP
WHERE HIREDATE 
BETWEEN TO_DATE('1981-01-01', 'YYYY-MM-DD') 
AND TO_DATE('1981-12-31', 'YYYY-MM-DD') ;

/*
SELECT *
FROM EMP
WHERE HIREDATE 
BETWEEN TO_DATE(#{startDte}, 'YYYY-MM-DD') 
AND TO_DATE(#{endDte}, 'YYYY-MM-DD') 
*/

SELECT TO_DATE('2023-07-20', 'YYYY-MM-DD') 
FROM dual;

SELECT * FROM STUDENT02 s ;

SELECT *
FROM STUDENT02 
WHERE name LIKE '%'||''||'%'
AND (kor+eng+math)/3 BETWEEN 50 AND 100;

SELECT COUNT(*)
FROM EMP
WHERE sal BETWEEN 2000 AND 3000;

SELECT max(sal)
FROM EMP 
WHERE deptno = 10;

SELECT EMPLOYEE_ID, FIRST_NAME , LAST_NAME,
	EMAIL, PHONE_NUMBER , HIRE_DATE , JOB_ID ,
	SALARY , COMMISSION_PCT , MANAGER_ID , DEPARTMENT_ID 
FROM EMPLOYEES e 
WHERE EMPLOYEE_ID = 100;


SELECT *
FROM JOBS j 
WHERE JOB_ID LIKE '%'||'P'||'%';

SELECT ename
FROM EMP
WHERE sal BETWEEN 1000 AND 2000;

SELECT CITY 
FROM LOCATIONS 
WHERE COUNTRY_ID like '%'||''||'%';

SELECT e.*, d.dname, d.loc
FROM EMP e, DEPT d ;

SELECT empno NO, ename name,
		sal salary
FROM emp02
order by empno;

SELECT *
FROM EMP02 e;

INSERT INTO EMP02 (empno, ename) VALUES(6000, '스폰지밥(마지막)'); 

SELECT deptno NO, dname name, loc location
FROM DEPT01 d 
ORDER BY DEPTNO ;